### ISSUE TITLE
apt Release should not have hashes of Release file

### ISSUE THREAD

**Issue by jrwest** [basho/node_package#161] opened 2014-08-26 14:18 UTC
According to a user, submitted by a different source so unfortunately I don't have much background:

"Your apt mirror Release should not include a md5sum/SHA/etc for the Release file itself, its invalid and causes some tools to fail. "

**Comment by jrwest** [comment] 2014-08-26 14:18
Apparently having the md5sum/sha/whatever causes some tools to break

**Comment by ooshlablu** [comment] 2014-08-27 15:59
Hmmm, so this was done wilfully in the scripts:

```
#signs apt release files as per Secure APT
rm -f dists/$DEBIAN_RELEASE/Release.gpg
gpg --use-agent -abs -o dists/$DEBIAN_RELEASE/Release.gpg dists/$DEBIAN_RELEASE/Release
gpg --use-agent --clearsign dists/$DEBIAN_RELEASE/Release
```

And it is definitely a valid way of doing things, and in fact the way that all modern debian based distros work: https://wiki.debian.org/SecureApt

I'm guessing that the user didn't pull down the key as per the docs: http://docs.basho.com/riak/latest/ops/building/installing/debian-ubuntu/#Installing-From-Apt-Get

MD5, SHA, etc are also required for ANY file in the repo: https://wiki.debian.org/RepositoryFormat#MD5Sum.2C_SHA1.2C_SHA256

This is also expected behavior from `apt-ftparchive`

@jaredmorrow can you weigh in?

**Comment by jaredmorrow** [comment] 2014-08-27 17:24
Reading the docs, this looks like we are doing it correctly.  I'm closing.

**Closed as completed by jaredmorrow** 2014-08-27 17:24 UTC
